on:
  pull_request_target:
    types: [opened]

name: Pull Request opened

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: step-security/assign-author@main